name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: check var
        run:
          echo ${{ github.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.workspace }}

      - name: Fetch and reset branch
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}-main
