name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: check title and body
        run:
          echo ${{ github.event.pull_request.title }}
          echo ${{ github.event.pull_request.body }}

      - name: Fetch and reset branch
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github }}-main
