name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Fetch and reset branch
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}


      - name: Get Last PR Title and Body
        id: pr_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_DATA=$(gh api repos/${{ github.repository }}/pulls --jq 'map(select(.base.ref == "${{ github.ref_name }}")) | sort_by(.merged_at) | reverse | .[0]')
          PR_TITLE=$(echo "$PR_DATA" | jq -r '.title')
          PR_BODY=$(echo "$PR_DATA" | jq -r '.body')

          echo "title=$PR_TITLE" >> $GITHUB_ENV
          echo "body=$PR_BODY" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}-main
          title: ${{ env.title }}
          body: ${{ env.body }}
