name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: check var
        run:
          echo ${{ github.sha }}

      - name: Fetch and reset branch
        run: |
          git fetch origin
          git reset --hard origin/${{ github.ref_name }}

      - name: Get Last Commit Message
        id: last_commit
        run: |
          LAST_COMMIT_MSG=$(git log origin/${{ github.ref_name }} -1 --pretty=%B)
          echo "commit_message=$LAST_COMMIT_MSG" >> $GITHUB_ENV

      - name: Fetch PR Data
        id: fetch_pr
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: "https://api.github.com/search/issues?q=sha:${{ github.sha }}"
          configuration: '{"method": "GET", "headers": { "Accept": "application/vnd.github.v3+json" }}'

      - name: Get PR Number
        id: pr_number
        run: |
          RESPONSE=$(curl -s "https://api.github.com/search/issues?q=sha:${{ github.sha }}")
          PR_NUMBER=$(echo '${{ steps.fetch_pr.outputs.data }}' | jq -r '.items[0].number')
          PR_BODY=$(echo "$RESPONSE" | jq -r '.items[0].body')
          PR_TITLE=$(echo "$RESPONSE" | jq -r '.items[0].title')
          PR_URL=$(echo "$RESPONSE" | jq -r '.items[0].html_url')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "PR_BODY=$PR_BODY" >> $GITHUB_ENV
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
          echo "PR_URL=$PR_URL" >> $GITHUB_ENV

      - name: check variable
        run:
          echo ${{ env.PR_NUMBER }}
          echo ${{ env.PR_BODY }}
          echo ${{ env.PR_TITLE }}
          echo ${{ env.PR_URL }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ github.ref_name }}-main
          title: "${{ env.commit_message }} (to main)"
