name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.ref_name }}
          git reset --hard ${{ github.ref_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main-promotion
