name: Create Main Sync Pull Request
on:
  push:
    branches:
      - "release-*"

jobs:
  syncMain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Fetch Lastest Change
        run: |
          git fetch origin

      - name: Get Last Commit Message
        id: last_commit
        run: |
          LAST_COMMIT_MSG=$(git log origin/${{ github.ref_name }} -1 --pretty=%B)
          echo "commit_message=$LAST_COMMIT_MSG" >> $GITHUB_ENV

      - name: Extract PR Number from Commit Message
        id: pr_number
        run: |
          PR_NUMBER=$(echo "${{ env.commit_message }}" | grep -oE "\(#([0-9]+)\)" | sed -E 's/\(#([0-9]+)\)/\1/')
          if [ -z "$PR_NUMBER" ]; then
            echo "No PR number found, setting to 'N/A'"
            PR_NUMBER="N/A"
          fi
          echo "pr_number=$PR_NUMBER" >> $GITHUB_ENV
          echo "pr_url=https://github.com/${{ github.repository }}/pull/$PR_NUMBER" >> $GITHUB_ENV

      - name: Create new branch from main
        run: |
          NEW_BRANCH="main-${{ github.ref_name }}-${{ github.sha }}"
          echo "new_branch_name=$NEW_BRANCH" >> $GITHUB_ENV
          
          git checkout -b "$NEW_BRANCH"

      - name: Cherry-pick the latest commit from release branch
        run: |
          git cherry-pick --strategy=recursive -X theirs ${{ github.sha }}

      - name: Commit & Push new branch
        run: |
          git add .
          git commit -m "Cherry-picked commit from ${{ github.ref_name }} with unresolved conflicts" || echo "No changes to commit"
          git push origin ${{ env.new_branch_name }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: main-${{ github.ref_name }}-${{ github.sha }}
          title: "${{ env.commit_message }} (to main)"
          body: "Automated Cherry-picked From PR [#${{ env.pr_number }}](${{ env.pr_url }})"